import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How Veyra collects, uses, and protects your information — written plainly, because privacy policies should be readable.",
  alternates: { canonical: "/privacy" },
  openGraph: { title: "Privacy Policy — Veyra", url: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      updated="September 2026"
      intro="We collect as little as possible, use it only for what you'd expect when you buy software, and never sell it. This page explains exactly what that means — in plain language, section by section."
      summary={[
        { label: "Collected", value: "Email, order and licence records, device identifiers for activations" },
        { label: "Never done", value: "Sold, rented, or shared for third-party marketing" },
        { label: "Retention", value: "Order and licence records kept for legal and warranty periods" },
        { label: "Your rights", value: "Access, correct, export, or delete — handled within 30 days" },
      ]}
      sections={[
        {
          heading: "Scope of this policy",
          body: (
            <p>
              This policy covers the {site.name} website, customer accounts,
              product downloads, and the licence activation service used by our
              desktop products. {site.name} is a {site.parent} brand; the terms{" "}
              &ldquo;we&rdquo;, &ldquo;us&rdquo;, and &ldquo;our&rdquo; refer to
              the {site.parent} team operating {site.name}.
            </p>
          ),
        },
        {
          heading: "Information we collect",
          body: (
            <>
              <p>
                <strong>Order information.</strong> When you purchase, our
                payment processor, Razorpay, collects what checkout requires —
                your email address and payment details. Card numbers are handled
                entirely by Razorpay and never touch our servers. We receive and
                store your email, the product purchased, the amount paid, and
                the order&rsquo;s status, so we can deliver your licence and
                files.
              </p>
              <p>
                <strong>Account information.</strong> If you create a customer
                account, we store your email address, an optional display name,
                and a password credential managed by our authentication
                provider. Nothing else is required.
              </p>
              <p>
                <strong>Licence and device data.</strong> When you activate a
                product on a machine, we record the licence key, the purchase
                email, a random per-install device identifier generated by the
                application, and activation timestamps. This exists for one
                purpose: enforcing the seat limit you purchased. The device
                identifier is a random string — it is not a hardware fingerprint
                and cannot identify you or your machine.
              </p>
              <p>
                <strong>Download records.</strong> When you download a product
                you own, we log the product, version, and time so we can support
                you and measure which releases are in use.
              </p>
              <p>
                <strong>Mailing-list email.</strong> If you request a free
                resource such as the client acquisition audit, we store your
                email address and the page it came from. Nothing else.
              </p>
              <p>
                <strong>Basic analytics.</strong> We use privacy-respecting,
                aggregate analytics to see which pages are read. No cross-site
                tracking, no advertising pixels, no profiling.
              </p>
            </>
          ),
        },
        {
          heading: "How we use information",
          body: (
            <ul>
              <li>To process payments, deliver products, and issue licences</li>
              <li>To enforce seat limits and handle activation, deactivation, and refunds</li>
              <li>To send transactional email you&rsquo;ve triggered — receipts, delivery, and licence notices</li>
              <li>To answer support requests and diagnose problems</li>
              <li>To understand, in aggregate, how the site and products are used</li>
            </ul>
          ),
        },
        {
          heading: "What we never do",
          body: (
            <p>
              We never sell, rent, or share your email address or order data
              with third parties for their marketing. We don&rsquo;t send
              unrequested promotional emails beyond the resource you asked for,
              and every marketing email we send includes a working unsubscribe
              link. Transactional emails about a purchase you made (receipt,
              delivery, refund) are sent regardless of subscription status,
              because they are part of the transaction.
            </p>
          ),
        },
        {
          heading: "Service providers",
          body: (
            <>
              <p>
                A small number of infrastructure providers process data on our
                behalf, under our instructions and their own data-processing
                terms:
              </p>
              <ul>
                <li>
                  <strong>Supabase</strong> — database, authentication, and
                  file storage for accounts, orders, licences, and downloads
                </li>
                <li>
                  <strong>Razorpay</strong> — payment processing at checkout
                </li>
                <li>
                  <strong>Resend</strong> — transactional email delivery
                </li>
                <li>
                  <strong>Cloudflare</strong> — hosting, content delivery, and
                  network security
                </li>
              </ul>
              <p>
                Access on our side is limited to the people who build the
                product and answer your emails.
              </p>
            </>
          ),
        },
        {
          heading: "Cookies and local storage",
          body: (
            <p>
              We use only strictly necessary cookies — the session cookie that
              keeps you signed in to your account, and the cart state stored in
              your own browser. There are no advertising or third-party tracking
              cookies, and nothing to accept or reject in a banner, because
              nothing beyond the essentials is set.
            </p>
          ),
        },
        {
          heading: "Data retention and security",
          body: (
            <>
              <p>
                Order, licence, and activation records are retained for as long
                as your licence is valid and as required for tax, accounting,
                and warranty obligations. Mailing-list records are kept until
                you unsubscribe. Support correspondence is kept for up to two
                years.
              </p>
              <p>
                Data is stored with the providers listed above, in transit over
                TLS and at rest on their encrypted infrastructure. Our database
                enforces row-level access rules so customer records are visible
                only to their owner and to authorised administration.
              </p>
            </>
          ),
        },
        {
          heading: "Your rights",
          body: (
            <p>
              You can ask us to show, correct, export, or delete your personal
              data at any time by writing to{" "}
              <a href={`mailto:${site.contact.email}`}>{site.contact.email}</a>.
              Requests are handled within 30 days, usually the same week.
              Deleting an account does not erase the order and licence records
              we are legally required to keep, but it does remove your profile
              and mailing-list presence.
            </p>
          ),
        },
        {
          heading: "Changes to this policy",
          body: (
            <p>
              If this policy changes materially, we&rsquo;ll update the date
              above and — where the change affects you directly — email you
              before it takes effect.
            </p>
          ),
        },
      ]}
    />
  );
}
