/**
 * Lead-magnet delivery — the 25-Point Client Acquisition Audit PDF.
 *
 * Sent by POST /api/subscribe when someone hands us an email address.
 * The PDF itself is generated by scripts/build-checklist-pdf.mjs and
 * embedded as base64 (src/lib/email/checklist-pdf.ts) — it never gets a
 * public URL, so the email really is the only way in, and the Cloudflare
 * Workers runtime (no filesystem) can attach it with zero I/O.
 *
 * Without RESEND_API_KEY configured the email renders to the server
 * console like every other transactional send — local/dev runs exercise
 * the full flow without credentials.
 *
 * Server-only: reads RESEND_API_KEY. Never import from client components.
 */

import "server-only";
import {
  CHECKLIST_PDF_BASE64,
  CHECKLIST_PDF_FILENAME,
} from "@/lib/email/checklist-pdf";
import { siteUrl } from "@/lib/email/purchase";

function fromAddress(): string {
  return process.env.VEYRA_EMAIL_FROM || "Veyra <hello@veyra.co>";
}

export type ChecklistSendResult = { ok: boolean; error: string | null };

export async function sendChecklistEmail(to: string): Promise<ChecklistSendResult> {
  const subject = "Your 25-Point Client Acquisition Audit (PDF)";

  const text = [
    `Your copy of the 25-Point Client Acquisition Audit is attached.`,
    ``,
    `How to use it:`,
    `1. Circle yes or no for each of the 25 points — honestly.`,
    `2. Tally your yeses per phase and overall.`,
    `3. The phase with the fewest yeses is where growth leaks. Fix that`,
    `   one thing this week, before anything else.`,
    ``,
    `Prefer it scored for you? The interactive Growth Audit asks 18`,
    `questions and returns your score, phase breakdown, and priority`,
    `list in about three minutes: ${siteUrl()}/audit`,
    ``,
    `Questions? Just reply to this email.`,
    ``,
    `— Veyra`,
  ].join("\n");

  const html = `<div style="font-family:Georgia,serif;max-width:520px;margin:0 auto;color:#17150f;line-height:1.6">
  <p style="font-size:12px;letter-spacing:.12em;text-transform:uppercase;color:#8a8474">Veyra · Free resource</p>
  <h1 style="font-size:26px;margin:6px 0 14px">Your audit checklist is attached.</h1>
  <p style="font-size:14px;margin:0 0 16px">Twenty-five yes/no checks across the six phases of client growth — build, acquire, sell, deliver, retain, grow. One honest <i>no</i> costs more than ten polished <i>yes</i>es.</p>
  <div style="background:#f4f2ec;border:1px solid #e7e4da;border-radius:8px;padding:16px 18px;margin:0 0 18px">
    <div style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:#8a8474;margin-bottom:8px">How to use it</div>
    <ol style="font-size:14px;padding-left:18px;margin:0">
      <li style="margin-bottom:6px">Circle <b>yes</b> or <b>no</b> for each point — honestly.</li>
      <li style="margin-bottom:6px">Tally your yeses per phase and overall.</li>
      <li>The phase with the fewest yeses is where growth leaks. Fix that one thing this week.</li>
    </ol>
  </div>
  <p style="font-size:14px;margin:0 0 18px">Prefer it scored for you? The <a href="${escapeHtml(siteUrl())}/audit" style="color:#2f5d3a">interactive Growth Audit</a> asks 18 questions and returns your score, phase breakdown, and priority list in about three minutes.</p>
  <p style="font-size:13px;color:#6f6a5d">Questions? Just reply to this email.</p>
  <p style="font-size:13px;color:#8a8474;margin-top:14px">— Veyra · no spam, no drip campaign</p>
</div>`;

  const key = process.env.RESEND_API_KEY;
  if (!key) {
    console.log(
      `\n[email:console] TO ${to}\nSUBJECT ${subject}\nATTACHMENT ${CHECKLIST_PDF_FILENAME} (${Math.round((CHECKLIST_PDF_BASE64.length * 3) / 4 / 1024)} KB)\n${"-".repeat(60)}\n${text}\n${"-".repeat(60)}`
    );
    return { ok: true, error: null };
  }

  try {
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: fromAddress(),
        to: [to],
        subject,
        html,
        text,
        attachments: [
          {
            filename: CHECKLIST_PDF_FILENAME,
            content: CHECKLIST_PDF_BASE64,
            content_type: "application/pdf",
          },
        ],
      }),
      cache: "no-store",
    });
    const body = (await res.json().catch(() => ({}))) as { id?: string; message?: string };
    if (!res.ok || !body.id) {
      const error = body.message ?? `Resend HTTP ${res.status}`;
      console.error(`[email] checklist send failed for ${to}: ${error}`);
      return { ok: false, error };
    }
    return { ok: true, error: null };
  } catch (err) {
    const error = err instanceof Error ? err.message : "network";
    console.error(`[email] checklist send error for ${to}:`, err);
    return { ok: false, error };
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
